name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Chromium
      run: npx playwright install --with-deps chromium
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
    - name: Build app
      run: npm run build
    - name: Run Playwright tests
      env:
        ANVIL_FORK_URL: ${{ secrets.ANVIL_FORK_URL }}
        TEST_ACCOUNT_MNEMONIC: ${{ secrets.TEST_ACCOUNT_MNEMONIC }}
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
